#!/usr/bin/env zsh

SCRIPTPATH=`pwd`

ln -sf $SCRIPTPATH/dotemacs/env0der ~/.emacs.d/private/env0der
ln -sf $SCRIPTPATH/dotemacs/.spacemacs ~/.spacemacs
ln -sf $SCRIPTPATH/.zprezto ~/.zprezto

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

ln -sf $SCRIPTPATH/.zshrc ~/.zshrc
ln -sf $SCRIPTPATH/.zpreztorc ~/.zpreztorc
ln -sf $SCRIPTPATH/.ctags ~/.ctags
ln -sf $SCRIPTPATH/.editrc ~/.editrc
ln -sf $SCRIPTPATH/.pryrc ~/.pryrc
ln -sf $SCRIPTPATH/.tmux.conf ~/.tmux.conf
mkdir -p ~/.boot
ln -sf $SCRIPTPATH/.boot/profile.boot ~/.boot/profile.boot
ln -sf $SCRIPTPATH/.hammerspoon ~/.hammerspoon
