#!/usr/bin/env zsh

SCRIPTPATH=`pwd`

ln -sf $SCRIPTPATH/dotemacs/env0der ~/.emacs.d/private/env0der
ln -sf $SCRIPTPATH/dotemacs/.spacemacs ~/.spacemacs
ln -sf $SCRIPTPATH/.zshrc ~/.zshrc
ln -sf $SCRIPTPATH/.ctags ~/.ctags
ln -sf $SCRIPTPATH/.editrc ~/.editrc
ln -sf $SCRIPTPATH/.pryrc ~/.pryrc
ln -sf $SCRIPTPATH/.tmux.conf ~/.tmux.conf
